Added function to delete models
LucidtechAI/las-sdk-python pull request #55
Opened 2021-05-27 13:56 UTC by MartinBJoh

Function for deleting models through the DELETE endpoint. Added test as well based on the test written for secrets which was similar in delete requirements.

2021-05-27 15:42 UTC, augustak requested changes
Can you update the changelog and SDK version as well?

2021-05-27 15:42 UTC, augustak commented on las/client.py
> +        >>> client.delete_asset('<model_id>')
```suggestion
        >>> client.delete_model('<model_id>')
```

2021-05-27 16:22 UTC, MartinBJoh commented
> Can you update the changelog and SDK version as well?

Done

2021-05-28 08:05 UTC, augustak approved these changes

2021-05-28 08:05 UTC, merged